### ISSUE TITLE
Full lyrics

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/alittleteapot.im#2]
It would be nice if when I went to this page, the teapot animation looped, but with each loop it would pour out the next verse. (Ideally, this should be done in sync with the music from issue #1)

**Comment by corbanmailloux** [comment]
I do agree that the animation should loop. Different lines of the song is good, but the sync would be difficult...

**Comment by MichaelWashburnJr** [comment]
I believe in you :)
